---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  query:
    options:
      query:
        base-path: /jaeger
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: jaeger
spec:
  prefix: /jaeger
  service: jaeger-query.seldon:16686
