kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8003
networking:
  disableDefaultCNI: true
  podSubnet: "10.15.240.0/20"
  apiServerAddress: "1.0.0.1"
  apiServerPort: 26443
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  metadata:
    name: config
  kubeReserved:
      cpu: "300m"
      memory: "300Mi"
      ephemeral-storage: "1Gi"
  kubeReservedCgroup: "/kube-reserved"
  systemReserved:
      cpu: "300m"
      memory: "300Mi"
      ephemeral-storage: "1Gi"
  evictionHard:
      memory.available:  "200Mi"
      nodefs.available: "10%"
  featureGates:
      DynamicKubeletConfig: true
      RotateKubeletServerCertificate: true
---
  apiVersion: kubeadm.k8s.io/v1beta2
  metadata:
    name: config
  kind: ClusterConfiguration
  networking:
    serviceSubnet: "10.12.0.0/14"
    podSubnet: "10.15.240.0/20"
