version: 2
updates:
- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - adriangonz
  ignore:
  - dependency-name: azure-storage-blob
    versions:
    - ">= 12.a, < 13"
  - dependency-name: black
    versions:
    - ">= 21.4b0.a, < 21.5"
  - dependency-name: coverage
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: coverage
    versions:
    - "> 5.2, < 5.3"
  - dependency-name: flake8
    versions:
    - "> 3.8.1, < 3.9"
  - dependency-name: flake8
    versions:
    - "> 3.9.0, < 3.10"
  - dependency-name: grpcio-reflection
    versions:
    - ">= 1.35.a, < 1.36"
  - dependency-name: grpcio-reflection
    versions:
    - ">= 1.37.a, < 1.38"
  - dependency-name: jaeger-client
    versions:
    - ">= 4.3.a, < 4.4"
  - dependency-name: mypy-protobuf
    versions:
    - ">= 1.21.a, < 1.22"
  - dependency-name: opentracing
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: pandas
    versions:
    - "> 1.0.1, < 1.1"
  - dependency-name: pandas
    versions:
    - "> 1.1.0, < 1.2"
  - dependency-name: pandas
    versions:
    - ">= 1.2.a, < 1.3"
  - dependency-name: pillow
    versions:
    - "> 6.2.0, < 6.3"
  - dependency-name: pillow
    versions:
    - "> 7.1.1, < 7.2"
  - dependency-name: pillow
    versions:
    - ">= 8.2.a, < 8.3"
  - dependency-name: pytest
    versions:
    - "> 5.3.1, < 5.4"
  - dependency-name: pytest
    versions:
    - "> 5.4.2, < 5.5"
  - dependency-name: pytest
    versions:
    - "> 6.2.2, < 6.3"
  - dependency-name: tornado
    versions:
    - "> 4.5.3"
  - dependency-name: urllib3
    versions:
    - ">= 1.26.a, < 1.27"
  - dependency-name: cryptography
    versions:
    - 3.4.6
    - 3.4.7
  - dependency-name: grpcio-tools
    versions:
    - 1.36.0
    - 1.36.1
  - dependency-name: pillow
    versions:
    - 8.1.2
  - dependency-name: tenacity
    versions:
    - 7.0.0
  - dependency-name: pip-licenses
    versions:
    - 3.3.1
  - dependency-name: grpcio-reflection
    versions:
    - 1.36.0
  - dependency-name: mypy
    versions:
    - "0.812"
  - dependency-name: coverage
    versions:
    - "5.5"
  - dependency-name: mypy-protobuf
    versions:
    - "1.24"
- package-ecosystem: gomod
  directory: "/executor"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - adriangonz
- package-ecosystem: gomod
  directory: "/operator"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - adriangonz
  ignore:
  - dependency-name: sigs.k8s.io/controller-runtime
    versions:
    - 0.8.2
    - 0.8.3
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.5
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.5
    - 1.11.0
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.15.1
  - dependency-name: k8s.io/apiextensions-apiserver
    versions:
    - 0.20.4
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.4
  - dependency-name: k8s.io/api
    versions:
    - 0.20.4
  - dependency-name: github.com/go-logr/logr
    versions:
    - 0.4.0
