apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: myabtest
  namespace: seldon
spec:
  annotations:
    seldon.io/executor: "true"
  name: myabtest
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          imagePullPolicy: IfNotPresent
          name: classifier-1
          resources:
            requests:
              memory: 1Mi
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
        terminationGracePeriodSeconds: 20
    - metadata:
        labels:
          version: v2
      spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          imagePullPolicy: IfNotPresent
          name: classifier-2
          resources:
            requests:
              memory: 1Mi
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
        terminationGracePeriodSeconds: 20
    engineResources: {}
    explainer:
      containerSpec:
        name: ""
        resources: {}
    graph:
      children:
      - endpoint:
          service_host: localhost
          service_port: 9000
          type: REST
        implementation: UNKNOWN_IMPLEMENTATION
        name: classifier-1
        type: MODEL
      - endpoint:
          service_host: myabtest-myabtest-classifier-2-seldonio-mock-classifier-1-0.seldon.svc.cluster.local.
          service_port: 9001
          type: REST
        implementation: UNKNOWN_IMPLEMENTATION
        name: classifier-2
        type: MODEL
      endpoint: {}
      implementation: RANDOM_ABTEST
      name: myabtest
      parameters:
      - name: ratioA
        type: FLOAT
        value: "0.5"
      type: UNKNOWN_TYPE
    labels:
      version: myabtest
    name: myabtest
    replicas: 1
    svcOrchSpec: {}
