apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: mymodel
  namespace: seldon
spec:
  annotations:
    seldon.io/executor: "true"
    seldon.io/engine-log-message-type: seldon.message.pair
    seldon.io/engine-log-messages-externally: "false"
    seldon.io/engine-log-requests: "false"
    seldon.io/engine-log-responses: "false"
    seldon.io/headless-svc: "false"
  name: mymodel
  predictors:
  - componentSpecs: 
    - spec:
        containers:
        - env:
          - name: LOG_LEVEL
            value: INFO
          image: seldonio/mock_classifier_grpc:1.3
          imagePullPolicy: IfNotPresent
          name: classifier
          resources:
            requests:
              memory: 1Mi
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
        terminationGracePeriodSeconds: 1
    engineResources: {}
    explainer:
      containerSpec:
        name: ""
        resources: {}
    graph:
      endpoint:
        service_host: localhost
        service_port: 9000
        type: GRPC
      implementation: UNKNOWN_IMPLEMENTATION
      name: classifier
      type: MODEL
    labels:
      fluentd: "true"
      version: v1
    name: mymodel
    replicas: 1
    svcOrchSpec:
      resources:
        requests:
          cpu: 100m
