apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: triton
spec:
  protocol: kfserving
  predictors:
  - graph:
      children: []
      endpoint:
        type: REST
        service_host: 0.0.0.0
        service_port: 9000
      implementation: TRITON_SERVER
      modelUri: gs://seldon-models/trtis/simple-model
      name: simple
      type: MODEL      
    name: simple
    replicas: 1
