apiVersion: v1
description: |
  Chart to deploy a model in Seldon Core.

  The chart bli bla blu
keywords:
  - kubernetes
  - machine-learning
name: seldon-single-model
sources:
  - https://github.com/SeldonIO/seldon-core
appVersion: 1.1.1-rc
version: 0.2.0
