
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: graph-metadata-output
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/metadata-generic-node:0.3
          name: node-output-transformer
          env:
          - name: MODEL_METADATA
            value: |
              ---
              name: node-output-transformer
              versions: [ generic-node/v0.3 ]
              platform: seldon
              inputs:
              - messagetype: tensor
                schema:
                  names: [transformer-input]
              outputs:
              - messagetype: tensor
                schema:
                  names: [transformer-output]                          
        - image: seldonio/metadata-generic-node:0.3
          name: node
          env:
          - name: MODEL_METADATA
            value: |
              ---
              name: node
              versions: [ generic-node/v0.3 ]
              platform: seldon
              inputs:
              - messagetype: tensor
                schema:
                  names: [node-input]
              outputs:
              - messagetype: tensor
                schema:
                  names: [transformer-input]       
    graph:
      name: node-output-transformer
      type: OUTPUT_TRANSFORMER
      children:
      - name: node
        type: MODEL
        children: []   
    name: example
    replicas: 1
