
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: graph-metadata-single
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/metadata-generic-node_rest:0.3
          name: model
          env:
          - name: MODEL_METADATA
            value: |
              ---
              name: single-node
              versions: [ generic-node/v0.3 ]
              platform: seldon
              inputs:
              - messagetype: tensor
                schema:
                  names: [node-input]
              outputs:
              - messagetype: tensor
                schema:
                  names: [node-output]
    graph:
      name: model
      type: MODEL
      children: []        
    name: example
    replicas: 1
