ambassador:
  enabled: true
  singleNamespace: false
engine:
  grpc:
    port: 5001
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/engine
    tag: 0.4.2-SNAPSHOT
  logMessagesExternally: false
  port: 8000
  prometheus:
    path: prometheus
  securityContext:
    enabled: true
  serviceAccount:
    name: default
  user: 8888
image:
  pullPolicy: Always
  registry: docker.io
  repository: seldonio/seldon-core-operator
  tag: 0.5
istio:
  enabled: false
  gateway: seldon-gateway
predictiveUnit:
  port: 9000
rbac:
  create: true
serviceAccount:
  create: true
  name: seldon-manager
usageMetrics:
  enabled: false
webhook:
  certManager:
    enabled: true
  secretProvided: false
  ca:
    crt: Cg==
  tls:
    crt: Cg==
    key: Cg==
