apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: seldon
  name: seldon-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seldon-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: seldon-system
