apiVersion: v1
data:
  credentials: "{\n   \"gcs\" : {\n       \"gcsCredentialFileName\": \"gcloud-application-credentials.json\"\n   },\n   \"s3\" : {\n       \"s3AccessKeyIDName\": \"awsAccessKeyID\",\n       \"s3SecretAccessKeyName\": \"awsSecretAccessKey\"\n   }\n}"
kind: ConfigMap
metadata:
  labels:
    app: seldon
    control-plane: seldon-controller-manager
  name: seldon-config
  namespace: seldon-system
