{{- if not .Values.certManager.enabled -}}
apiVersion: v1
data:
  ca.crt: '{{ .Values.webhook.ca.crt }}'
  tls.crt: '{{ .Values.webhook.tls.crt }}'
  tls.key: '{{ .Values.webhook.tls.key }}'
kind: Secret
metadata:
  name: seldon-webhook-server-cert
  namespace: '{{ .Release.Namespace }}'
type: kubernetes.io/tls
{{- end }}
