apiVersion: v1
kind: Service
metadata:
  labels:
    app: seldon
  name: seldon-webhook-service
  namespace: seldon-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: seldon
    control-plane: seldon-controller-manager
