apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    certmanager.k8s.io/inject-ca-from: seldon-system/seldon-serving-cert
  creationTimestamp: null
  labels:
    app: seldon
  name: seldon-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: seldon-webhook-service
      namespace: seldon-system
      path: /validate-machinelearning-seldon-io-v1alpha2-seldondeployment
  failurePolicy: Fail
  name: vseldondeployment.kb.io
  rules:
  - apiGroups:
    - machinelearning.seldon.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - seldondeployments
